--Author : HP (HP)
--Date : 06-13/2017
--Notes : New schema for INFORMATICA DVO repository 

whenever oserror exit SQL.OSCODE rollback
whenever sqlerror exit SQL.SQLCODE rollback

set autocommit off timing on echo on feedback on termout on

spool cr_usr_DVO_OWN.log

CREATE USER DVO_OWN
  IDENTIFIED BY DVO_OWN1
  DEFAULT TABLESPACE TBS_EDH_TRX_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE FW_USER_APP
  ACCOUNT UNLOCK;

  GRANT RESOURCE TO DVO_OWN;
  ALTER USER DVO_OWN DEFAULT ROLE NONE;

  GRANT ALTER SESSION TO DVO_OWN;
  GRANT CREATE CLUSTER TO DVO_OWN;
  GRANT CREATE INDEXTYPE TO DVO_OWN;
  GRANT CREATE JOB TO DVO_OWN;
  GRANT CREATE OPERATOR TO DVO_OWN;
  GRANT CREATE PROCEDURE TO DVO_OWN;
  GRANT CREATE SEQUENCE TO DVO_OWN;
  GRANT CREATE SESSION TO DVO_OWN;
  GRANT CREATE SYNONYM TO DVO_OWN;
  GRANT CREATE TABLE TO DVO_OWN;
  GRANT CREATE TRIGGER TO DVO_OWN;
  GRANT CREATE TYPE TO DVO_OWN;
  GRANT CREATE VIEW TO DVO_OWN;
  GRANT DEBUG ANY PROCEDURE TO DVO_OWN;
  GRANT DEBUG CONNECT SESSION TO DVO_OWN;
  GRANT UNLIMITED TABLESPACE TO DVO_OWN;
  
  ALTER USER DVO_OWN QUOTA UNLIMITED ON TBS_EDH_TRX_DATA;
  ALTER USER DVO_OWN QUOTA UNLIMITED ON TBS_EDH_TRX_IDX;

spool off
exit
